// Generates lib/data/room_definitions.dart from assets/rooms.bin + room metadata.
// Run: dart run tools/generate_room_data.dart
// ignore_for_file: avoid_print
import 'dart:io';
import 'dart:typed_data';

// Room metadata (from game_data.dart)
const _rooms = <int, _RoomMeta>{
  1: _RoomMeta('Entrance Hall', 'in the entrance hall', ['N', 'W', 'E']),
  2: _RoomMeta('Dining Room', 'in a large dining room', ['S', 'N', 'E']),
  3: _RoomMeta('Kitchen', 'in the kitchen', ['E', 'N', 'W']),
  4: _RoomMeta('Pantry', 'standing in the pantry', ['W', 'N', 'E']),
  5: _RoomMeta('Dark Corridor', 'in a dark eerie corridor', ['S', 'N', 'E']),
  6: _RoomMeta('Conservatory', 'in a conservatory', ['W', 'S', 'N']),
  7: _RoomMeta('Oak Panelled Study', 'in an oak panelled study', ['S', 'E', 'N']),
  8: _RoomMeta('Sitting Room', 'in a large sitting room', ['E', 'W', 'N']),
  9: _RoomMeta('Upstairs Hallway', 'standing in an upstairs hallway', ['S', 'E', 'N']),
  10: _RoomMeta('Guest Bedroom', 'in a guest bedroom', ['W', 'S', 'N']),
  11: _RoomMeta('Dressing Room', 'in a dressing room', ['S', 'N', 'E']),
  12: _RoomMeta('Annexe', 'in a small annexe', ['W', 'S', 'N']),
  13: _RoomMeta('Master Bedroom', 'in the master bedroom', ['S', 'E', 'N']),
  14: _RoomMeta('Icy Corridor', 'standing in an icy corridor', ['W', 'S', 'N']),
  15: _RoomMeta('Haunted Room', 'in a haunted room', ['S', 'E', 'N']),
  16: _RoomMeta('Library', 'in the library', ['W', 'S', 'N']),
  17: _RoomMeta('Secret Passageway', 'in a secret passageway', ['S', 'E', 'N']),
  18: _RoomMeta('Old Attic', 'in an old attic', ['W', 'S', 'N']),
  19: _RoomMeta('Tower', 'in a tower', ['W', 'E', 'N']),
  20: _RoomMeta('Cellar', 'in the cellar', ['E', 'S', 'W']),
  21: _RoomMeta('Wine Cellar', 'in the wine cellar', ['S', 'E', 'W']),
  22: _RoomMeta('Store Room', 'in a store room', ['E', 'S', 'W']),
  23: _RoomMeta('Crypt', 'in a crypt', ['E', 'S', 'W']),
  24: _RoomMeta('Underground Chamber', 'in an underground chamber', ['E', 'S', 'W']),
  25: _RoomMeta('Torture Chamber', 'in a torture chamber', ['E', 'S', 'W']),
  26: _RoomMeta('Dark Passage', 'in a dark passage', ['E', 'S', 'W']),
  27: _RoomMeta('Exit', 'outside the house!', ['E', 'S']),
};

class _RoomMeta {
  final String name;
  final String description;
  final List<String> exits;
  const _RoomMeta(this.name, this.description, this.exits);
}

void main() {
  final binPath = 'assets/rooms.bin';
  final outPath = 'lib/data/room_definitions.dart';

  final bytes = File(binPath).readAsBytesSync();
  final data = Uint8List.fromList(bytes);

  // Find all room locations
  final roomLocations = <int, (int start, int end)>{};
  for (int i = 0; i < data.length; i++) {
    final b = data[i];
    if (b >= 0xA0 && b <= 0xBB) {
      final roomId = b - 0xA0;
      // Find end
      int endOffset = data.length;
      for (int j = i + 1; j < data.length; j++) {
        if (data[j] >= 0xA0 && data[j] <= 0xBB) {
          endOffset = j;
          break;
        }
      }
      roomLocations[roomId] = (i, endOffset);
    }
  }

  final buf = StringBuffer();
  buf.writeln("import 'dart:typed_data';");
  buf.writeln();
  buf.writeln('/// Room definitions with bytecode extracted from original Atari cassette.');
  buf.writeln('/// Auto-generated by tools/generate_room_data.dart — do not edit by hand.');
  buf.writeln();
  buf.writeln('class RoomDefinition {');
  buf.writeln('  final int id;');
  buf.writeln('  final String name;');
  buf.writeln('  final String description;');
  buf.writeln('  final List<String> exits;');
  buf.writeln('  final Uint8List bytecode;');
  buf.writeln();
  buf.writeln('  RoomDefinition({');
  buf.writeln('    required this.id,');
  buf.writeln('    required this.name,');
  buf.writeln('    required this.description,');
  buf.writeln('    required this.exits,');
  buf.writeln('    required this.bytecode,');
  buf.writeln('  });');
  buf.writeln('}');
  buf.writeln();
  buf.writeln('final List<RoomDefinition> roomDefinitions = [');

  final sortedIds = roomLocations.keys.toList()..sort();
  for (final roomId in sortedIds) {
    final meta = _rooms[roomId];
    if (meta == null) continue;

    final (start, end) = roomLocations[roomId]!;
    final roomBytes = data.sublist(start, end);

    buf.writeln('  // -----------------------------------------------------------------------');
    buf.writeln('  // Room $roomId: ${meta.name}');
    buf.writeln('  // -----------------------------------------------------------------------');
    buf.writeln('  RoomDefinition(');
    buf.writeln('    id: $roomId,');
    buf.writeln("    name: '${meta.name}',");
    buf.writeln("    description: '${meta.description}',");
    buf.writeln("    exits: [${meta.exits.map((e) => "'$e'").join(', ')}],");
    buf.writeln('    bytecode: Uint8List.fromList([');

    _writeCommentedBytecode(buf, roomBytes, roomId);

    buf.writeln('    ]),');
    buf.writeln('  ),');
  }

  buf.writeln('];');

  final outDir = Directory('lib/data');
  if (!outDir.existsSync()) outDir.createSync(recursive: true);
  File(outPath).writeAsStringSync(buf.toString());
  print('Generated $outPath with ${sortedIds.length} rooms.');
}

void _writeCommentedBytecode(StringBuffer buf, Uint8List roomBytes, int roomId) {
  if (roomBytes.length < 5) return;

  // Header: marker + screenFill + 3 color bytes
  final screenFill = roomBytes[1];
  final c0 = roomBytes[2];
  final c1 = roomBytes[3];
  final c2 = roomBytes[4];
  buf.writeln('      // Header: room $roomId, screenFill=${_hex(screenFill)}, '
      'colors=[${_hex(c0)}, ${_hex(c1)}, ${_hex(c2)}]');
  buf.writeln('      ${_hexList(roomBytes, 0, 5)},');

  // Parse commands
  int i = 5;
  int currentColor = 1;

  while (i < roomBytes.length) {
    final byte = roomBytes[i];

    if (byte == 0xC8) {
      // Polyline with current color
      i++;
      final pts = _readPoints(roomBytes, i);
      final count = pts ~/ 2;
      final cmdLen = 1 + pts;
      buf.writeln('      // Polyline color=$currentColor, $count pts');
      buf.writeln('      ${_hexList(roomBytes, i - 1, cmdLen)},');
      i += pts;
    } else if (byte == 0xC9) {
      // Close+fill with current color
      if (i + 1 < roomBytes.length) {
        final offsetByte = roomBytes[i + 1];
        final ox = (offsetByte >> 4) & 0x0F;
        final oy = offsetByte & 0x0F;
        buf.writeln('      // Close+Fill color=$currentColor, offset=($ox,$oy)');
        buf.writeln('      ${_hexList(roomBytes, i, 2)},');
        i += 2;
      } else {
        break;
      }
    } else if (byte == 0xCA) {
      // Close+fill with specified color
      if (i + 2 < roomBytes.length) {
        final fillColor = roomBytes[i + 1];
        final offsetByte = roomBytes[i + 2];
        final ox = (offsetByte >> 4) & 0x0F;
        final oy = offsetByte & 0x0F;
        buf.writeln('      // Close+Fill fillColor=$fillColor, offset=($ox,$oy)');
        buf.writeln('      ${_hexList(roomBytes, i, 3)},');
        i += 3;
      } else {
        break;
      }
    } else if (byte == 0xCB) {
      // Flood fill current color at x,y
      if (i + 2 < roomBytes.length) {
        final x = roomBytes[i + 1];
        final y = roomBytes[i + 2];
        buf.writeln('      // FloodFill color=$currentColor at ($x,$y)');
        buf.writeln('      ${_hexList(roomBytes, i, 3)},');
        i += 3;
      } else {
        break;
      }
    } else if (byte == 0xCC) {
      // Flood fill pattern at x,y
      if (i + 3 < roomBytes.length) {
        final ab = roomBytes[i + 1];
        final x = roomBytes[i + 2];
        final y = roomBytes[i + 3];
        String desc;
        if (ab <= 3) {
          desc = 'solid color $ab';
        } else {
          desc = 'pattern ${(ab >> 6) & 3},${(ab >> 4) & 3},${(ab >> 2) & 3},${ab & 3}';
        }
        buf.writeln('      // FloodFill $desc at ($x,$y)');
        buf.writeln('      ${_hexList(roomBytes, i, 4)},');
        i += 4;
      } else {
        break;
      }
    } else if (byte >= 0xCD && byte <= 0xD0) {
      // Polyline with color 0-3
      currentColor = byte - 0xCD;
      i++;
      final pts = _readPoints(roomBytes, i);
      final count = pts ~/ 2;
      final cmdLen = 1 + pts;
      buf.writeln('      // Polyline color=$currentColor, $count pts');
      buf.writeln('      ${_hexList(roomBytes, i - 1, cmdLen)},');
      i += pts;
    } else if (byte < 0xA0) {
      // Implicit polyline
      final pts = _readPoints(roomBytes, i);
      if (pts >= 2) {
        final count = pts ~/ 2;
        buf.writeln('      // Implicit polyline color=$currentColor, $count pts');
        buf.writeln('      ${_hexList(roomBytes, i, pts)},');
        i += pts;
      } else {
        // Orphaned byte
        buf.writeln('      // Data byte');
        buf.writeln('      ${_hexList(roomBytes, i, 1)},');
        i++;
      }
    } else {
      // Stop byte
      break;
    }
  }
}

/// Count coordinate bytes (pairs of bytes < 0xA0) starting at [start].
int _readPoints(Uint8List buf, int start) {
  int count = 0;
  int i = start;
  while (i + 1 < buf.length) {
    if (buf[i] >= 0xA0 || buf[i] >= 0xC8) break;
    if (buf[i + 1] >= 0xA0 || buf[i + 1] >= 0xC8) break;
    count += 2;
    i += 2;
  }
  return count;
}

String _hex(int b) => '0x${b.toRadixString(16).toUpperCase().padLeft(2, '0')}';

String _hexList(Uint8List buf, int start, int length) {
  final end = (start + length).clamp(0, buf.length);
  return buf
      .sublist(start, end)
      .map((b) => _hex(b))
      .join(', ');
}
